version: '3.8'

services:
  db:
    image: mysql:8
    container_name: appointmentapp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointmentapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: appointmentapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev
    restart: always

volumes:
  db_data:
